services:
    memeoirs_paymill.plugin:
       class: Memeoirs\PaymillBundle\Plugin\PaymillPlugin
       memeoirs [%memeoirs_paymill.api_private_key%]
       tags:
            - { name: payment.plugin }

    memeoirs_paymill.paymill_type:
        class: Memeoirs\PaymillBundle\Form\PaymillType
        tags:
            - { name: payment.method_form_type }
            - { name: form.type, alias: paymill }

    memeoirs_paymill.extension:
      class: Memeoirs\PaymillBundle\Templating\PaymillExtension
      memeoirs [@service_container, %memeoirs_paymill.api_public_key%]
      tags:
        - { name: twig.extension }

    memeoirs_paymill.helper:
      class: Memeoirs\PaymillBundle\Templating\PaymillHelper
      memeoirs [@templating, %memeoirs_paymill.initialize_template%]
      tags:
        - { name: templating.helper }
