services:
    fm_payment_paymill.plugin:
       class: Fm\PaymentPaymillBundle\Plugin\PaymillPlugin
       arguments: [%fm_payment_paymill.api_private_key%]
       tags:
            - { name: payment.plugin }

    fm_payment_paymill.paymill_type:
        class: Fm\PaymentPaymillBundle\Form\PaymillType
        tags:
            - { name: payment.method_form_type }
            - { name: form.type, alias: paymill }

    fm_payment_paymill.extension:
      class: Fm\PaymentPaymillBundle\Templating\PaymillExtension
      arguments: [@service_container, %fm_payment_paymill.api_public_key%]
      tags:
        - { name: twig.extension }

    fm_payment_paymill.helper:
      class: Fm\PaymentPaymillBundle\Templating\PaymillHelper
      arguments: [@templating, %fm_payment_paymill.initialize_template%]
      tags:
        - { name: templating.helper }
